src/The-Occasion/Models/Mood.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace The_Occasion.Models
{
    public class Mood
    {
        [Key]
        public int MoodId { get; set; }

        public string MoodName { get; set; }
    }
}

src/The-Occasion/Models/Poem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace The_Occasion.Models
{
    public class Poem
    {
        [Key]
        public int PoemId { get; set; }

        [Required]
        [Display(Name ="Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name ="Author")]
        public string Author { get; set; }

        [Display(Name ="Collection")]
        public string Collection { get; set; }

        [Required]
        [Display(Name = "Date Published")]
        public int PubDate { get; set; }

        [Display(Name ="Form")]
        public int FormId { get; set; }
        public Form Form { get; set; }

        public int MoodId { get; set; }
        public Mood Mood { get; set; }

        [Display(Name = "Topic")]
        public int TopicId { get; set; }
        public Topic Topic { get; set; }

        public string Lines { get; set; }
        public ICollection<UserSelection> UserSelections { get; set; }

        public string RhymeScheme { get; set; }

        
    }
}

src/The-Occasion/Models/PoemViewModels/AllPoemsViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using The_Occasion.Data;

namespace The_Occasion.Models.PoemViewModels
{
    public class AllPoemsViewModel
    {
        public IEnumerable<Poem> AllPoems { get; set; }
        public AllPoemsViewModel(ApplicationDbContext ctx)
        {
            var context = ctx;
        }
        public List <Poem>UserPoems { get; set; }

        public string FormName { get; set; }

        public string MoodName { get; set; }

        public string TopicName { get; set; }

    }
}

src/The-Occasion/Models/PoemViewModels/SavedPoemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using The_Occasion.Data;

namespace The_Occasion.Models.PoemViewModels
{
    public class SavedPoemViewModel
    {

            public Poem Poem { get; set; }

            public Array LinesArray { get; set; }

            public List<Poem> OtherWorks = new List<Poem>();

            public UserSelection UserSelection { get; set; }

            public Author Author { get; set; }
            public string UserFullName { get; set; }
            public string Line1 { get; set; }
            public string Line2 { get; set; }
            public string Line3 { get; set; }


            public SavedPoemViewModel(ApplicationDbContext ctx)
            {
                var context = ctx;
            }
        }
    }

src/The-Occasion/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace The_Occasion.Models
{
    public class Topic
    {

        [Key]

        public int TopicId { get; set; }

        public string TopicName { get; set; }
    }
}

src/The-Occasion/Controllers/PoemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using The_Occasion.Data;
using The_Occasion.Models;
using The_Occasion.Models.PoemViewModels;
using The_Occasion.ExtensionMethods;
using Microsoft.Extensions.DependencyInjection;
using System.Text;
using Microsoft.EntityFrameworkCore.Internal;
using System.Runtime.Serialization.Formatters;
using System.IO;


namespace The_Occasion.Controllers
{
    public class PoemController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;

        private ApplicationDbContext context;

        private bool _authorExists(string name)
        {
            return context.Author.Count(a => a.Name == name) > 0;
        }

        private bool _userExists()
        {
            return _userManager.GetUserName(User) != null;
        }


        public PoemController(ApplicationDbContext ctx, UserManager<ApplicationUser> user)
        {
            _userManager = user;
            context = ctx;
        }

        [Authorize]
        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        public async Task<IActionResult> AllPoems()
        {
            AllPoemsViewModel model = new AllPoemsViewModel(context);
            model.AllPoems = await context.Poem.GroupBy(p => p.Title).Select(p => p.FirstOrDefault()).ToListAsync();
            return View(model);
        }

        public IActionResult Picky()
        {
            PickyPoemsViewModel model = new PickyPoemsViewModel(context);
            return View(model);
        }

        [Authorize]
        [HttpGet("/Poem/Curate/{moodId}/{topicId}/{formId}")]

        public async Task<IActionResult> Curate([FromRoute]int moodId, [FromRoute]int topicId, [FromRoute]int formId)
        {
            var curatedPoems = await context.Poem.Where(p => p.MoodId == moodId && p.TopicId == topicId && p.FormId == formId).ToListAsync();
            AllPoemsViewModel model = new AllPoemsViewModel(context);
            model.AllPoems = curatedPoems;
            return View(model);

        }

        [Authorize]
        public async Task<IActionResult> MyPoems()
        {
            UserSelectionViewModel model = new UserSelectionViewModel(context);
            //identify the current user, which will be coerced to the userId
            var user = await GetCurrentUserAsync();
            //identify all of the user selections by the user Id
            var userName = user.UserName;
            var userFullName = user.FirstName + " " + user.LastName;
            var userSelections = await context.UserSelection.Where(u => u.User == user).ToListAsync();
            //grab all of the poems from the database
            var Poems = await context.Poem.ToListAsync();
            //match user selection poem id's with poem ideas and add each poem to the view model
            foreach (var u in userSelections)
            {
                foreach (var p in Poems)
                {
                    if (p.PoemId == u.PoemId)
                    {
                        model.UserPoems.Add(p);
                    }
                }
            }

            foreach (var poem in model.UserPoems)
            {
                if (poem.Author == userFullName && poem.FormId == 120)
                {
                    model.UserGeneratedHaikus.Add(poem);
                }

                else if (poem.Author == userFullName && poem.FormId == 118)
                {
                    model.UserGeneratedSonnets.Add(poem);
                }

                else
                {
                    model.UserLikedPoems.Add(poem);
                }
            }

            model.UserLikedPoems = model.UserLikedPoems.DistinctBy(w => w.Title).OrderBy(w => w.Title).ToList();
            model.UserGeneratedSonnets = model.UserGeneratedSonnets.DistinctBy(w => w.Title).OrderBy(w => w.Title).ToList();
            model.UserGeneratedHaikus = model.UserGeneratedHaikus.DistinctBy(w => w.Title).OrderBy(w => w.Title).ToList();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Mood([FromRoute] int? id)
        {
            AllPoemsViewModel model = new AllPoemsViewModel(context);
            model.AllPoems = await context.Poem.Where(p => p.MoodId == id).GroupBy(p => p.Title).Select(p => p.FirstOrDefault()).ToListAsync();
            var mood = await context.Mood.SingleOrDefaultAsync(m => m.MoodId == id);
            model.MoodName = mood.MoodName;
            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> Form([FromRoute] int? id)
        {
            AllPoemsViewModel model = new AllPoemsViewModel(context);
            model.AllPoems = await context.Poem.Where(p => p.FormId == id).GroupBy(p => p.Title).Select(p => p.FirstOrDefault()).ToListAsync();

            var form = await context.Form.SingleOrDefaultAsync(f => f.FormId == id);
            model.FormName = form.FormName;
            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> Topic([FromRoute] int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            AllPoemsViewModel model = new AllPoemsViewModel(context);
            model.AllPoems = await context.Poem.Where(p => p.TopicId == id).GroupBy(p => p.Title).Select(p => p.FirstOrDefault()).ToListAsync();
            var topic = await context.Topic.SingleOrDefaultAsync(t => t.TopicId == id);
            model.TopicName = topic.TopicName;

            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> Poem([FromRoute]int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SinglePoemViewModel model = new SinglePoemViewModel(context);
            Poem SinglePoem = await context.Poem.SingleOrDefaultAsync(p => p.PoemId == id);
            model.Poem = SinglePoem;
            string lineString = SinglePoem.Lines;
            var splitStrings = Regex.Split(lineString, "@@");
            model.LinesArray = splitStrings;
            var user = await GetCurrentUserAsync();
            if (_userExists())
            {

                var userFullName = user.FirstName + " " + user.LastName;
                model.UserFullName = userFullName;
            }
            if (_authorExists(SinglePoem.Author))
            {
                Author poemAuthor = await context.Author.Where(a => a.Name == SinglePoem.Author).FirstAsync();
                model.Author = poemAuthor;
            }

            else
            {
                model.Author = null;
            };

            var OtherWorks = await context.Poem.Where(p => p.Author == model.Poem.Author && p.Title != model.Poem.Title).ToListAsync();
            var OtherWorksUniqueTitles = OtherWorks.DistinctBy(w => w.Title).OrderBy(w => w.Title).ToList();
            model.OtherWorks = OtherWorksUniqueTitles;
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> SavedPoem([FromRoute]int? id)
        {

            SinglePoemViewModel model = new SinglePoemViewModel(context);
            Poem SinglePoem = await context.Poem.SingleOrDefaultAsync(p => p.PoemId == id);
            UserSelection userSelection = await context.UserSelection.Where(u => u.PoemId == SinglePoem.PoemId).FirstAsync();
            model.UserSelection = userSelection;
            model.Poem = SinglePoem;
            string lineString = SinglePoem.Lines;
           var splitStrings = Regex.Split(lineString, "@@");
            

            if (splitStrings.Last() == "")
            {
                splitStrings = splitStrings.Take(splitStrings.Count() - 1).ToArray();
            }
            model.LinesArray = splitStrings;

            var user = await GetCurrentUserAsync();
            var userFullName = user.FirstName + " " + user.LastName;
            Author author = new Author();
            author = await context.Author.Where(a => a.Name == SinglePoem.Author).FirstOrDefaultAsync();
            model.Author = author;
            model.UserFullName = userFullName;
            var OtherWorks = await context.Poem.Where(p => p.Author == model.Poem.Author && p.Title != model.Poem.Title).ToListAsync();
            var OtherWorksUniqueTitles = OtherWorks.DistinctBy(w => w.Title).OrderBy(w => w.Title).ToList();
            model.OtherWorks = OtherWorksUniqueTitles;
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Bored()
        {

            var AllPoems = await context.Poem.GroupBy(p => p.Title).Select(p => p.FirstOrDefault()).ToListAsync();
            SinglePoemViewModel model = new SinglePoemViewModel(context);
            Random random = new Random();
            int r = random.Next(AllPoems.Count);
            model.Poem = AllPoems[r];
            string lineString = model.Poem.Lines;
            var splitStrings = Regex.Split(lineString, "@@");
            model.LinesArray = splitStrings;
            return View(model);

        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Save([FromRoute] int id)
        {

            var user = await GetCurrentUserAsync();
            UserSelection userSelection = new UserSelection();
            userSelection.User = user;
            userSelection.PoemId = id;
            context.UserSelection.Add(userSelection);
            await context.SaveChangesAsync();
            return Ok();

src/The-Occasion/Views/Poem/AllPoems.cshtml
@model The_Occasion.Models.PoemViewModels.AllPoemsViewModel
@{
    ViewData["Title"] = "All The Dang Poems";
}

<h2 class="top-buffer">@ViewData["Title"]</h2>

    <div class="row poemrow">
@foreach (var poem in Model.AllPoems) { 
      
        
        <div class="col-md-6">
        <a asp-controller="Poem" asp-action="Poem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem=> poem.Title)</a></div>
        
        <div class="col-md-6">@Html.DisplayFor(modelItem => poem.Author)</div>
    



}
       </div>

src/The-Occasion/Views/Poem/Bored.cshtml
@model The_Occasion.Models.PoemViewModels.SinglePoemViewModel
@using Microsoft.AspNetCore.Identity
@using The_Occasion.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Ontological Resolution (for Now)";
}

<div class="row poemrow">
    <h3 class="title">@Html.DisplayFor(model => model.Poem.Title)</h3>

    @foreach (var line in Model.LinesArray)
    {
        <div class="col-md-12">@line</div>
    }
    <div class="col-md-6 author">@Html.DisplayFor(model => model.Poem.Author)</div>
    <div class="col-md-3 bottom-buffer"><button id="SaveBored" value="@Model.Poem.PoemId" class="btn btn-danger">Save to My Profile</button></div>
    <div class="col-md-3"><button id="Delete" value="@Model.Poem.PoemId" class="hidden btn btn-danger">Delete From My Profile</button></div>
    <div class="col-md-3 hidden bottom-buffer" id="ItsSaved2">Your Poem Has Been Saved!</div>
    <div class="col-md-3 bottom-buffer"><a class="btn btn-danger hidden" asp-controller="Home" asp-action="Index" id="GoHome2">Take Me Home</a></div>
        </div>

src/The-Occasion/Views/Poem/Curate.cshtml
@model The_Occasion.Models.PoemViewModels.AllPoemsViewModel



<div class="row poemrow">
<h3 class="title">Picky, Picky</h3>
    @if (Model.AllPoems.Count() > 0) {
    @foreach (var poem in Model.AllPoems)
    {


        <div class="col-md-6">
            <a asp-controller="Poem" asp-action="Poem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem => poem.Title)</a>
        </div>

        <div class="col-md-6">@Html.DisplayFor(modelItem => poem.Author)</div>

    }
    }
            else {
            <div class="col-md-6">Sorry, But That's Too Picky</div>
            <div class="col-md-3"><a class="btn btn-danger" asp-controller="Home" asp-action="Index" id="GoHome">Take Me Home</a></div>
    }
        

    
</div>

src/The-Occasion/Views/Poem/Form.cshtml
@model The_Occasion.Models.PoemViewModels.AllPoemsViewModel

<div class="row poemRow">
<h3 class="title">@Model.FormName<span>s</span></h3> 
    </div>


@foreach (var poem in Model.AllPoems)
{

    <div class="row poemRow top-buffer">
        <a asp-controller="Poem" asp-action="Poem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem => poem.Title)</a><div>@Html.DisplayFor(modelItem=>poem.Author)
        </div>
    </div>
}

src/The-Occasion/Views/Poem/Mood.cshtml
@model The_Occasion.Models.PoemViewModels.AllPoemsViewModel
<div class="row poemrow">
<h3 class="title">Poems for Your Mood: @Model.MoodName</h3> 
    </div>

   @foreach (var poem in Model.AllPoems)
   {

    <div class="row poemRow top-buffer">
        <a asp-controller="Poem" asp-action="Poem" asp-route-id="@poem.PoemId" class="poem-link">@Html.DisplayFor(modelItem => poem.Title)</a><div>
            @Html.DisplayFor(modelItem => poem.Author)
    </div>
</div>
   }

src/The-Occasion/Views/Poem/MyPoems.cshtml
@model The_Occasion.Models.PoemViewModels.UserSelectionViewModel

<div class="row poemRow top-buffer">
    <h4 class="title">Poems You Like</h4>
    @foreach (var poem in Model.UserLikedPoems)
    {

        <div class="col-md-12 line-saved">
            <span class="title-saved"><a class="title-saved" asp-controller="Poem" asp-action="SavedPoem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem => poem.Title)</a></span>
            <span class="author-saved">@Html.DisplayFor(modelItem => poem.Author)</span>
        </div>
    }

    <h4 class="title">Haikus Your Computer Wrote For You</h4>
    @foreach (var poem in Model.UserGeneratedHaikus)
    {
    <div class="col-md-12 line-saved">
        <span class="title-saved">
            <a asp-controller="Poem" asp-action="SavedPoem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem => poem.Title)</a>
        </span>

        <span class="author-saved">@Html.DisplayFor(modelItem => poem.Author)</span>
        </div>
    }

    <h4 class="title">Sonnets Your Computer Wrote For You</h4>
    @foreach (var poem in Model.UserGeneratedSonnets)
    {
        <div class="col-md-12 line-saved">
        <span class="title-saved">
            <a asp-controller="Poem" asp-action="SavedPoem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem => poem.Title)</a>
        </span>
            
        <span class="author-saved">@Html.DisplayFor(modelItem => poem.Author)</span>
            </div>
    }
</div>

src/The-Occasion/Views/Poem/Picky.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Identity

@model The_Occasion.Models.PoemViewModels.PickyPoemsViewModel
@{
    ViewData["Title"] = "Welcome to The Occasion";
}
<div class="row">
<div class="form-group findselect" id="formCurateselect">

    <div class="col-md-12">
        @Html.DropDownList("Forms.Id", @Model.FormId)
    </div>
</div>

<div class="form-group findselect" id="moodCurateselect">
    <div class="col-md-12">
        @Html.DropDownList("Moods.Id", @Model.MoodId)
    </div>
</div>

<div class="form-group findselect" id="topicCurateselect">
    <div class="col-md-12">
        @Html.DropDownList("Topics.Id", @Model.TopicId)
    </div>
</div>

<div class="text-center">
    <a class="btn btn-danger" id="CurateMe">Hit Me</a>
</div>

<div id="hereBePickyPoems"></div>
</div>

src/The-Occasion/Views/Poem/Poem.cshtml
@model The_Occasion.Models.PoemViewModels.SinglePoemViewModel
@using Microsoft.AspNetCore.Identity
@using The_Occasion.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "The Occasion";
}

<div class="row poemRow singlePoem">

<h3 class="title">@Html.DisplayFor(model => model.Poem.Title)</h3>

             @foreach (var line in Model.LinesArray)
             {
                <div class="col-lg-12 lines">@line</div>
             }       
    <div class="col-md-12 author lines top-buffer">@Html.DisplayFor(model => model.Poem.Author)</div>

        @if (Model.Author != null)
        {



<div class="col-md-12 lines top-buffer small-font">@Html.DisplayFor(model => model.Author.Bio)</div> 
        }

        else
        {
            <span></span>

        }

    @if(Model.OtherWorks.Count == 0)
    {
        <div class="col-lg-12 small-font">No Other Works By this Poet Appear in The Database</div>
    }

    else {
    <div class="col-lg-12 lines top-buffer">Other Works By This Author</div>
    
        @foreach (var poem in Model.OtherWorks)
    {
        <div class="col-lg-12 lines small-font"><a asp-controller="Poem" asp-action="Poem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem => poem.Title)</a></div>
    }

    }
        @if (UserManager.GetUserName(User) != null)
        {
        <div class="col-md-3 top-buffer"><button id="Save" value="@Model.Poem.PoemId" class="btn btn-danger">Save to My Profile</button></div>
        <div class="col-md-3"><button id="Delete" value="@Model.Poem.PoemId" class="hidden btn btn-danger">Delete From My Profile</button></div>
        <div class="col-md-3 hidden bottom-buffer" id="ItsSaved">Your Poem Has Been Saved!</div>
        <div class="col-md-3 bottom-buffer"><a class="btn btn-danger hidden" asp-controller="Home" asp-action="Index" id="GoHome">Take Me Home</a></div>
        }
        else
        {
            <div class="col-md-12">
            <a asp-controller="Account" asp-action="Register">Register</a><span> or </span> 
                <a asp-controller="Account" asp-action="Login">Login</a><span> to Save This Poem to Your Account</span> 
                </div>
        }
    </div>
 

src/The-Occasion/Views/Poem/SavedPoem.cshtml
@model The_Occasion.Models.PoemViewModels.SinglePoemViewModel
@using Microsoft.AspNetCore.Identity
@using The_Occasion.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "The Occasion";
}

<div class="row poemRow singlePoem">

    <input class="form-control hidden" value="@Model.Poem.PoemId" id="poemId"/>
    <div class = "hidden">@Model.Poem.PoemId</div>
    <div class="hidden" value="@Model.UserSelection.UserSelectionId" id="userSelectionId" /></div>
    <h3 class="title">@Html.DisplayFor(model => model.Poem.Title)</h3>
 

    @foreach (var line in Model.LinesArray)
    {
      <div class="col-lg-12 lines"><input class="form-control hidden" id="linesDiv" value="@line" />
         @line
    @if (Model.Poem.Author == Model.UserFullName && Model.Poem.FormId != 118)
    {
            <input class="form-control hidden edit-input" placeholder="Edit this line" id="edit-input"><button class="btn-xs edit">Edit</button>
    }
        else
        {
        <span></span>
        }
    </div>
    }
    <div class="col-md-12 author lines top-buffer">@Html.DisplayFor(model => model.Poem.Author)</div>

    @if (Model.Author != null)
    {



        <div class="col-md-12 lines top-buffer small-font">@Html.DisplayFor(model => model.Author.Bio)</div>
    }

    @if (Model.OtherWorks.Count == 0)
    {
        <div class="col-lg-12 small-font">No Other Works By this Poet Appear in The Database</div>
    }

    else
    {
        <div class="col-lg-12 lines top-buffer">Other Works By This Author</div>
    }

        @foreach (var poem in Model.OtherWorks)
        {
            <div class="col-lg-12 lines small-font"><a asp-controller="Poem" asp-action="Poem" asp-route-id="@poem.PoemId">@Html.DisplayFor(modelItem => poem.Title)</a></div>
        }

    @if (UserManager.GetUserName(User) != null)
    {
        <div class="col-md-3"><button id="Delete" value="@Model.UserSelection.UserSelectionId" class="btn btn-danger">Delete From My Profile</button></div>
      @if (Model.Poem.Author == Model.UserFullName && Model.Poem.FormId != 118)
      {
    <div class="col-md-3"><a class="btn btn-danger" id ="update">Update</a></div>
      }
      else
      {
          <span></span>

      }
        <div class="col-md-3 top-buffer hidden" id="SavedAgain">Your poem has been saved (again).</div>
        <div class="col-md-3"><button id="Save" value="@Model.Poem.PoemId" class="hidden btn btn-danger">Eh, Maybe I Do Want It. Save It Again, Please.</button></div>
        <div class="col-md-3 bottom-buffer hidden" id="GoHome3"><a class="btn btn-danger" asp-controller="Home" asp-action="Index">Take Me Home</a></div>
    }
    else
    {
        <div class="col-md-12">
            <a asp-controller="Account" asp-action="Register">Register</a><span> or </span>
            <a asp-controller="Account" asp-action="Login">Login</a><span> to Save This Poem to Your Account</span>
        </div>
    }
 


   

src/The-Occasion/Views/Poem/TooPicky.cshtml
#
# TooPicky.ps1
#

src/The-Occasion/Views/Poem/Topic.cshtml
@model The_Occasion.Models.PoemViewModels.AllPoemsViewModel

<div class="row poemRow">
<h3 class="title">Poems About @Model.TopicName</h3> 
</div>

@foreach (var poem in Model.AllPoems)
{

    <div class="row poemRow top-buffer">
        <a asp-controller="Poem" asp-action="Poem" asp-route-id="@poem.PoemId" class="poem-link">@Html.DisplayFor(modelItem => poem.Title)</a><div>
            @Html.DisplayFor(modelItem => poem.Author)
        </div>
    </div>
}